/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.*;

/**
 *
 * @author Bienvenido Daniel
 */
public class GestionarCli extends javax.swing.JPanel {

    /**
     * Creates new form GestionarCli
     */
    ListaClientes clientes=new ListaClientes();
    public GestionarCli() {
        initComponents();
        //BAgregar.setVisible(false);
        
    }
    public ListaClientes getARClientes(){
        return clientes;
    }
    public void setARClientes(ListaClientes clientes){
        this.clientes=clientes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BAgregar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLAnuncio = new javax.swing.JLabel();
        BRecorrerC = new javax.swing.JButton();
        jSPane1 = new javax.swing.JScrollPane();
        TAMostrar = new javax.swing.JTextArea();
        TDC = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        TNC = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TCC = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TANotaC = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        CBAgregar = new javax.swing.JComboBox<>();
        BVerificar = new javax.swing.JButton();
        BEliminaC = new javax.swing.JButton();
        CB_TC = new javax.swing.JComboBox<>();

        setLayout(null);

        BAgregar.setText("Agregar Cliente");
        BAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAgregarActionPerformed(evt);
            }
        });
        add(BAgregar);
        BAgregar.setBounds(80, 292, 130, 24);

        jLabel19.setText("Tipo:");
        add(jLabel19);
        jLabel19.setBounds(47, 227, 27, 16);

        jLAnuncio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLAnuncio);
        jLAnuncio.setBounds(162, 254, 331, 20);

        BRecorrerC.setText("Recorrer Clientes");
        BRecorrerC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRecorrerCActionPerformed(evt);
            }
        });
        add(BRecorrerC);
        BRecorrerC.setBounds(447, 292, 138, 24);

        TAMostrar.setEditable(false);
        TAMostrar.setColumns(20);
        TAMostrar.setRows(5);
        jSPane1.setViewportView(TAMostrar);

        add(jSPane1);
        jSPane1.setBounds(26, 327, 597, 132);
        add(TDC);
        TDC.setBounds(101, 175, 171, 24);

        jLabel20.setText("Dejar comentario");
        add(jLabel20);
        jLabel20.setBounds(462, 68, 95, 16);
        add(TNC);
        TNC.setBounds(101, 118, 171, 24);

        jLabel17.setText("Nombre:");
        add(jLabel17);
        jLabel17.setBounds(26, 122, 48, 16);

        TCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCCActionPerformed(evt);
            }
        });
        add(TCC);
        TCC.setBounds(101, 64, 171, 24);

        jLabel16.setText("Codigo:");
        add(jLabel16);
        jLabel16.setBounds(31, 68, 43, 16);

        jLabel18.setText("DNI:");
        add(jLabel18);
        jLabel18.setBounds(47, 179, 27, 16);

        TANotaC.setColumns(20);
        TANotaC.setRows(5);
        jScrollPane5.setViewportView(TANotaC);

        add(jScrollPane5);
        jScrollPane5.setBounds(400, 119, 223, 129);

        jLabel15.setText("Clientes");
        add(jLabel15);
        jLabel15.setBounds(269, 19, 60, 16);

        jLabel21.setText("Comentario:");
        add(jLabel21);
        jLabel21.setBounds(302, 122, 68, 16);

        CBAgregar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO", "SI" }));
        CBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBAgregarActionPerformed(evt);
            }
        });
        add(CBAgregar);
        CBAgregar.setBounds(575, 63, 48, 26);

        BVerificar.setText("Verificar");
        BVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BVerificarActionPerformed(evt);
            }
        });
        add(BVerificar);
        BVerificar.setBounds(290, 64, 110, 24);

        BEliminaC.setText("Eliminar Cliente");
        BEliminaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEliminaCActionPerformed(evt);
            }
        });
        add(BEliminaC);
        BEliminaC.setBounds(267, 292, 129, 24);

        CB_TC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nuevo", "Recurrente", "VIP" }));
        add(CB_TC);
        CB_TC.setBounds(128, 222, 144, 26);
    }// </editor-fold>//GEN-END:initComponents

    private void BAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAgregarActionPerformed
        String permiso=(String) CBAgregar.getSelectedItem();
        String codCliente=TCC.getText();
        if(!clientes.ExisteElemento(codCliente)){
            String nombre=TNC.getText();
            String dni=TDC.getText();
            int tipoCliente=CB_TC.getSelectedIndex()+1;
            Cliente client;
            if(permiso.equals("SI")){
                String nota=TANotaC.getText();
                client=new Cliente(codCliente,nombre,dni,tipoCliente,nota);
                clientes.Agregar(client);
                jLAnuncio.setText("Se agrego cliente");
            }
            else{
                client=new Cliente(codCliente,nombre,dni,tipoCliente);
                clientes.Agregar(client);
                jLAnuncio.setText("Se agrego cliente");
            }
            TCC.setText(null);
            TNC.setText(null);
            TDC.setText(null);
            TANotaC.setText(null);
        }
        else{
            jLAnuncio.setText("El código digitado ya está en uso.");
        }
        
    }//GEN-LAST:event_BAgregarActionPerformed

    private void BRecorrerCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRecorrerCActionPerformed
        TAMostrar.setText("hola");
        TAMostrar.setText(clientes.Recorrer());
    }//GEN-LAST:event_BRecorrerCActionPerformed

    private void TCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCCActionPerformed

    }//GEN-LAST:event_TCCActionPerformed

    private void CBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBAgregarActionPerformed

    private void BVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVerificarActionPerformed
        String codCliente=TCC.getText(), mensaje;
        if(clientes.ExisteElemento(codCliente)){
            mensaje="Cliente encontrado:\n";
            mensaje+=clientes.Mostrar(codCliente).Mostrar();
            TAMostrar.setText(mensaje);
        }
        else{
            mensaje="No existe cliente con el código digitado.";
            jLAnuncio.setText(mensaje);
        }
        
    }//GEN-LAST:event_BVerificarActionPerformed

    private void BEliminaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliminaCActionPerformed
        String codCliente=TCC.getText();
        jLAnuncio.setText(clientes.EliminarElemento(codCliente));
    }//GEN-LAST:event_BEliminaCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAgregar;
    private javax.swing.JButton BEliminaC;
    private javax.swing.JButton BRecorrerC;
    private javax.swing.JButton BVerificar;
    private javax.swing.JComboBox<String> CBAgregar;
    private javax.swing.JComboBox<String> CB_TC;
    private javax.swing.JTextArea TAMostrar;
    private javax.swing.JTextArea TANotaC;
    private javax.swing.JTextField TCC;
    private javax.swing.JTextField TDC;
    private javax.swing.JTextField TNC;
    private javax.swing.JLabel jLAnuncio;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JScrollPane jSPane1;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
